
name: deploy

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  deploy:
    uses: cc332030/node/.github/workflows/deploy.yml@master
    secrets:
      NODE_VERSION: '18'
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      ORIGIN_PATH: build
      REMOTE_PATH: /home/program/nginx/html/tools2
