
name: deploy

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    uses: cc332030/node/.github/workflows/deploy.yml@master
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
    with:
      remote-path: /home/program/nginx/html/tools
